# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160728_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title2',
        ),
    ]
