# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160808_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment1',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
