# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('attack', models.CharField(max_length=10)),
                ('defense', models.CharField(max_length=10)),
                ('ptype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=8, max_length=3)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.user'),
        ),
    ]
