# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20160718_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_location', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='user',
        ),
        migrations.AddField(
            model_name='capture',
            name='pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.user'),
        ),
    ]
