# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import pokemon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20160728_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default='01075114391', max_length=15, validators=[pokemon.validators.phone_number_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, validators=[pokemon.validators.max(5)]),
        ),
    ]
