# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import pokemon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_auto_20160728_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_number',
            field=models.IntegerField(default=123402, max_length=10, validators=[pokemon.validators.post]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=15, validators=[pokemon.validators.phone_number_validator()]),
        ),
    ]
