# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import pokemon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_auto_20160801_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(validators=[pokemon.validators.phone_number_validator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='post_number',
            field=models.IntegerField(validators=[pokemon.validators.post]),
        ),
    ]
