# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import pokemon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_auto_20160801_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='post_number',
        ),
        migrations.AddField(
            model_name='user',
            name='post_number1',
            field=models.CharField(default='1234124', max_length=10, validators=[pokemon.validators.post()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='post_number2',
            field=models.CharField(default='123', max_length=10, validators=[pokemon.validators.post_api()]),
            preserve_default=False,
        ),
    ]
