# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import pokemon.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_auto_20160801_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post_number2',
            field=models.CharField(max_length=10, validators=[pokemon.validators.post_api(True)]),
        ),
    ]
